MUST_UART=0
MUST_TX=0
MUST_RX=1
MUST_CTRL=15
MUST_ADDR=4
MUST_PREFIX='inverter'
MUST_INTERVAL=5

PYLONTECH_UART=1
PYLONTECH_TX=4
PYLONTECH_RX=5
PYLONTECH_BATT=3
PYLONTECH_PREFIX='battery'
PYLONTECH_INTERVAL=60

MQTT_HOST='192.168.42.1'
WIFI_SSID='wifi'
WIFI_PASSWORD='password'

ERROR_FILE='errors.txt'

try:
    from .local_settings import *
except ImportError:
    pass
